'''
Given a grid of mine locations (where . are empty cells and x are mines), your goal is to display the grid like it appears if you win the game.
Each position is a digit indicating the number of mines bordering it (including diagonals). The mines (x) don't appear anymore. Mines and positions that do not border any mines both appear as empty cells (.).
Input
Line 1 : an integer w for the width of the grid.
Line 2 : an integer h for the height of the grid.
Next h lines : each line of the minefield, with dots (.) or mines (x).
Output
h lines of width w showing the completed game of Minesweeper.
Constraints
1 <= w <= 30
1 <= h <= 30
Example
Input

16
9
................
................
................
................
................
....x...........
................
................
................

Output

................
................
................
................
...111..........
...1.1..........
...111..........
................
................

------------------------------



10
7
..........
.x...x...x
..x......x
.....x....
..x.x...x.
x.........
.x...x...x

111.111.11
1.211.1.2.
12.1222.2.
.2232.1122
12.2.211.1
.322221122
2.1.1.1.1.


------------------------------


16
11
..xxxxxx..x.x...
.xx...xxx....xxx
x.xxxx.xxx...xxx
xxxxxxxxxx..xxxx
...xx..x..xxxx..
xx.xx.xxxx..x...
xxxxxx.....x..xx
xx......xxx..xxx
xxxxxxxxxxxxxxxx
xxx.xxx......xx.
........xxxxxxxx

13......32.2.332
2..766...4223...
.7....7...214...
..........44....
456..66.75....42
..6..5....45.432
......34554.34..
..766544...55...
................
...5...556667..5
23222322........

--------------------------------


26
12
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................



'''
w = int(input())
h = int(input())
for i in range(h):
    line = input()
